# Generated by Django 4.2.5 on 2023-09-25 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_verification_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('set_active', 'Can block users')]},
        ),
    ]
