# Generated by Django 4.2.5 on 2023-09-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=250, verbose_name='заголовок')),
                ('body', models.TextField(verbose_name='содержимое')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='blogs/', verbose_name='превью(изображение)')),
                ('date_create', models.DateField(blank=True, null=True, verbose_name='дата создания')),
                ('views_count', models.IntegerField(default=0, verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блоги',
            },
        ),
    ]
