# Generated by Django 4.2.5 on 2023-09-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='period',
            field=models.CharField(choices=[('Ежедневно', 'Ежедневно'), ('Раз в неделю', 'Раз в неделю'), ('Раз в месяц', 'Раз в месяц')], max_length=20, verbose_name='периодичность рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена')], default=('Создана', 'Создана'), max_length=20, verbose_name='статус рассылки'),
        ),
    ]
