# Generated by Django 4.2.5 on 2023-09-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0005_mailing_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglog',
            name='status',
            field=models.BooleanField(max_length=20, verbose_name='статус попытки'),
        ),
    ]
